### ISSUE TITLE
MinKnow RPC client

### ISSUE THREAD

**Issue by esteinig** [esteinig/Streamfish#2]
## Tasks

- [x] contact the `MinKnow API` server and get the version
- [x] do this inside docker network or via host-container bridge
- [x] implement authentication through developer token or alternatives
- [x] implement `ManagerClient` in `MinknowClient` 
- [x] implement `DataClient` in `MinknowClient`

## Channels and clients

See how performance is impacted when multiplexing requests - it is recommended to clone channels in `tonic`. For the `MinknowClient` we have implemented two attributes - `channels` which holds all connected `ActiveChannels` so they can be cloned when needing to instantiate an RPC service client: `ManagerServiceClient::new(self.channel.clone(), config.token.clone())`. 

A consistent channel to the `ManagerService` and instance of `ManagerServiceClient` on port 9502 (default from configuration) is created when instantiating the `MinknowClient` through the connection method:  `MinknowClient::connect(config)`.

## Authentication interceptor

Authentication is added with a custom `AuthInterceptor` that adds the correct meta-data field for authentication, so that each client wrapper implements e.g. `ManagerServiceClient<InterceptedService<Channel, AuthInterceptor>>` instead of `ManagerServiceClient<Channel>`

## ManagerClient

Wrap requests to and responses from the `ManagerService` in a `ManagerClient` struct that uses the RPC `ManagerServiceClient` methods to make the requests. 

## DataClient

Wrap requests to and responses from the `DataService` in a `DataClient` struct that uses the RPC `DataServiceClient` methods to make the requests. `DataClient::from_minknow_client` can be used to open a new secure channel with the correct configuration and ports for a position that have been requested during `MinknowClient::connect` and are available in `positions` with `positions.get_secure_ports(position_name)`.

If we want to implement a high level `MinknowClient` method such as `stream_channel_state_log(...)` that uses a new `DataClient` connection, we can simply pass `self` and the position name to the instantiation: `DataClient::from_minknow_client(self, position_name)`.
